### ISSUE TITLE
Wrong Play Area Dimesions reported 

### ISSUE THREAD

**Issue by SmartCarrion** [ExtendRealityLtd/Tilia.CameraRigs.TrackedAlias.Unity#41]
### Environment

* Code source: github
* Code version: 1.5.1
* Platform version: Unity 2019.4.13f
* 3rd party dependencies: Oculus Quest and link cable, Steam, Windows PC.

### Steps to reproduce

Start a new project, add Tracked alias and Unity XR camera rig.  Write a script to print your PlayAreaDimensions to the console.

Attach Oculus Quest 1/2 to PC with USB cable and enable Oculus Link.  Make a large play area boundary within the Quest guardian tool.

Play the game and note the console.

### Expected behavior

You should see the boundaries of the large Oculus guardian you set up.

### Current behavior

You visually see the large Oculus guardian boundaries, but Tilia reports the small default 1x1 boundaries from Steam.

**Comment by SmartCarrion** [comment]
This is mostly not Tilia's fault and could be fixed in the future as Oculus lines up more with OpenXR, but who knows.  Is there any function to detect the headset type and load up a different SDK?  The CameraRigSwitcher seems like only a manual switcher.

**Comment by thestonefox** [comment]
What script are you writing to get the play area dimensions?

**Comment by SmartCarrion** [comment]
essentially:
public PlayAreaDimensionsExtractor playAreaDimensionsExtractor;
public void AdjustRoomToPlayspace()
      {
playAreaDimensionsExtractor.DoExtract();
Debug.Log("Adjusting to room size: " +  playAreaDimensionsExtractor.Result.ToString());
}

**Comment by thestonefox** [comment]
I'm guessing Unity 2019.4 has removed the UnityEngine.Experimental.XR Boundary.TryGetDimensions method

try seeing what that outputs.

**Comment by SmartCarrion** [comment]
Ok, i'll research some more and try a few different calls to see if I can get anything to report the right value.  It is possible it is just hidden to Unity too, and we can't punch through OpenXR/Steam to Oculus.

**Comment by SmartCarrion** [comment]
UnityEngine.Experimental.XR Boundary.TryGetDimensions outputs the same thing:

Trying another room extractor: (1.0, 0.0, 1.0)
UnityEngine.Debug:Log(Object)

**Comment by thestonefox** [comment]
That would mean that the issue is with the underlying Unity stuff and not with Tilia because tilia just reports what unity tells it.

**Comment by SmartCarrion** [comment]
I ran into issues getting it from Oculus directly, looks like they might be pulling from the same place anyway.  Maybe switching to the XR Plugin Management system will help somehow, I'll try that. Closing as it is unlikely to need a direct Tilia fix.
