### ISSUE TITLE
Tracked Alias Getting Started Documentation refers to old property name CameraRigs

### ISSUE THREAD

**Issue by bpeck** [ExtendRealityLtd/Tilia.CameraRigs.TrackedAlias.Unity#66]
### Environment

* Code source: https://registry.npmjs.org
* Code version: "io.extendreality.tilia.camerarigs.trackedalias.unity": "1.6.8", "io.extendreality.tilia.camerarigs.spatialsimulator.unity": "1.4.16"
* Platform version: Unity 2020.3.19f1
* 3rd party dependencies:

### Steps to reproduce

* Create blank 3D project, add the above Tilia packages to the project manifest file.
* Follow getting started documentation found at https://github.com/ExtendRealityLtd/Tilia.CameraRigs.TrackedAlias.Unity/tree/master/Documentation/HowToGuides/AddingATrackedAlias
* In particular, step 2:

> Select the CameraRigs.TrackedAlias GameObject in the Unity Hierarchy window then increase the CameraRigs -> Elements -> Size property by 2 on the Tracked Alias Facade component.

* The documentation calls for adding a elements to a CameraRigs property on the CameraRigs.TrackedAlias game object. This property does not exist. The Tracked Alias Settings section of the game object must be used instead to complete this step.

### Expected behavior

Getting Started documentation reflects latest changes to the game object structure, and specifies how to use Tracked Alias Settings

### Current behavior

Getting Started documentation in step 2 refers to property names that no longer exist, namely the CameraRigs property.

### In Closing
Cheers, have a nice day

**Comment by thestonefox** [comment]
The guide was written for Unity 2018.3, the guide is still relevant for that version of Unity.

It should still be usable for newer versions of unity too.

You may have an issue if you're using Unity 2020 as there is a bug with Unity that prevents it from working when you first open a project. You need to restart unity and reopen your project

This is the bug listed on Unity's bug tracker: https://issuetracker.unity3d.com/issues/unity-does-not-execute-code-weavers-when-its-opened-for-the-first-time
